import type { Metadata } from 'next';
import './globals.css';

import { PokemonProvider } from '@/context/pokemonContext';
import { DarkModeProvider } from '@/context/darkModeContext';

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
//https://tailwindcss.com/docs/dark-mode
export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<DarkModeProvider>
				<body className={inter.className}>
					<PokemonProvider>{children}</PokemonProvider>
				</body>
			</DarkModeProvider>
		</html>
	);
}
